#!/bin/bash -ex

if [ -z "$CPP_INCLUDE_DIR" ];
then
    CPP_INCLUDE_DIR=/usr/include/c++
fi

if [ -z "${BOOST_INCLUDE_DIR}" ];
then
    BOOST_INCLUDE_DIR=/usr/include/boost
fi


## STL
mkdir -p cpp_stl
cp -R "$CPP_INCLUDE_DIR" cpp_stl
# it is not necessary to rename headers without an extension                                        
# replace the "namespace std _GLIBCXX_VISIBILITY(default)" with "namespace std"                     
pushd cpp_stl
find . -type f | xargs sed -i 's/namespace std _GLIBCXX_VISIBILITY(default)/namespace std/'       
popd
ctags -f stl_tags -R --c++-kinds=+p --fields=+iaS --extra=+q --language-force=C++ -I _GLIBCXX_NOEXCEPT cpp_stl

## BOOST
ctags -f boost_tags -R --c++-kinds=+p --fields=+iaS --extra=+q --language-force=C++ "${BOOST_INCLUDE_DIR}"
